platform :ios, '13.0'
ENV['SWIFT_VERSION'] = '5.0'
use_frameworks!

workspace 'InManageRatingSDKExamplespace'

def shared_pods
#  pod 'Alamofire'
end

target 'InManageRatingSDKExample' do
  shared_pods
end

target 'InManageRatingSDK' do
   project 'InManageRatingSDK/InManageRatingSDK.xcodeproj'
  shared_pods
end

##bitcode enable
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end

